config/routes.rb
Deets::Application.routes.draw do
  get 'deets/:id' => 'deets#show'
  post 'personacallback' => 'home#persona_callback'
  get 'oauth2callback' => 'home#google_oauth_callback'
  get 'profile' => 'profile#edit'
  put 'profile' => 'profile#update'
  post 'remove_link' => 'profile#remove_link'
  post 'add_link' => 'profile#add_link'
  get 'logout' => 'home#logout', as: 'logout'
  root to: 'home#index'
end

app/models/person.rb
require 'digest/md5'

class Person < ActiveRecord::Base
  serialize :links, ActiveRecord::Coders::Hstore

  attr_accessible :birth, :email, :lastfm, :links, :name, :slug

  def self.create_for_email email
    Person.create email: email,
      slug: Digest::MD5.hexdigest(email),
      name: email.split("@")[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login
  helper_method :current_person

  def require_login
    unless logged_in?
      session[:initial_url] = request.url
      redirect_to root_url
    end
  end

  def logged_in?
    !!current_person
  end

  def current_person
    return @current_person if @current_person
    return unless session[:email]
    @current_person = Person.find_by_email session[:email]
    @current_person = Person.create_for_email session[:email] unless @current_person
    @current_person
  end
end

app/controllers/deets_controller.rb
class DeetsController < ApplicationController
  skip_filter :require_login

  def show
    deet = {
      name: 'unknown',
      email: 'unknown',
      birth: 0,
      links: {}
    }
    person = Person.find_by_slug params[:id]
    deet = person.attributes if person
    render json: deet
  end
end

app/controllers/home_controller.rb
require 'persona'
require 'google_oauth'

class HomeController < ApplicationController
  include Persona
  include GoogleOauth

  skip_filter :require_login

  def index
    if logged_in?
      redirect_url = session[:initial_url] || :profile
      session[:initial_url] = nil
      redirect_to redirect_url
    else
      @google_login = google_oauth_url
      render layout: 'landing'
    end
  end

  def logout
    session[:email] = nil
    redirect_to root_url
  end

  def persona_callback
    response = {}
    verify_persona { |email, response| session[:email] = email }
    render json: response
  end

  def google_oauth_callback
    verify_google_oauth { |email| session[:email] = email }
    redirect_to '/'
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def update
    if current_person.update_attributes params[:person]
      redirect_to profile_url, notice: 'Profile successfully updated.'
    else
      render :edit
    end
  end

  def add_link
    current_person.links[params[:new_key]] = params[:new_url]
    current_person.save
    render json: {}
  end

  def remove_link
    current_person.links.delete params[:key]
    current_person.save
    render json: {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
a href="https://github.com/markryall/deets"
  img style="position: absolute; top: 0; left: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_left_gray_6d6d6d.png" alt="Fork me on GitHub"

div.row
  div class="span4 offset2"
    a href="#{@google_login}"
      img style="width: 200px; padding: 20px" src="assets/sign-in-with-google.png"

div.row
  div class="span4 offset2"
    a#authenticate
      img style="width: 200px; padding: 20px" src="assets/persona_sign_in_red.png"

app/views/layouts/application.html.slim
doctype html
html
  head
    title deets
  link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"
    = stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap.min.css'
    = stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap-responsive.min.css'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  body
    div.navbar.navbar-fixed-top
      div.navbar-inner
        div.container
          ul.nav.pull-right
            li
              = link_to "logout #{@current_person.email}", logout_url

    div.container
      = yield

    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.0/jquery.min.js'
    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/js/bootstrap.min.js'
    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/knockout/2.2.1/knockout-min.js'
    = javascript_include_tag 'application'
    = yield :javascript_includes

app/views/layouts/landing.html.slim
doctype html
html
  head
    title Deets
    = stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap.min.css'
    = stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap-responsive.min.css'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  body
    div.container
      = yield

    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.0/jquery.min.js'
    = javascript_include_tag 'https://login.persona.org/include.js'
    = javascript_include_tag 'application'